POST http://localhost:8080/events
content-type: application/json

{
  "name": "Test event 3",
  "description": "A test event 3",
  "location": "A test location 3",
  "dateTime": "2025-01-01T15:30:00Z"
}