DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc5MzU2MjMsInVzZXJJZCI6MX0.EDQu4DvcOyEagySVdLxo72_01kDFB-TetttVTICOFJo